server:
  port: 1992

spring:
  application:
    name: mm-board-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://mm-config-server:1881"

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml